import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const roboto_mono = localFont({
    src: [
        {
            path: '../public/fonts/roboto_mono/RobotoMono-Regular.ttf',
            weight: '400',
            style: 'normal',
        },
        {
            path: '../public/fonts/roboto_mono/RobotoMono-Medium.ttf',
            weight: '500',
            style: 'normal',
        },
        {
            path: '../public/fonts/roboto_mono/RobotoMono-SemiBold.ttf',
            weight: '600',
            style: 'normal',
        },
        {
            path: '../public/fonts/roboto_mono/RobotoMono-Bold.ttf',
            weight: '700',
            style: 'normal',
        },
    ],
    variable: '--font-roboto-mono',
})

const geist = localFont({
    src: [
        {
            path: '../public/fonts/geist/Geist-Regular.ttf',
            weight: '400',
            style: 'normal',
        },
        {
            path: '../public/fonts/geist/Geist-Medium.ttf',
            weight: '500',
            style: 'normal',
        },
        {
            path: '../public/fonts/geist/Geist-SemiBold.ttf',
            weight: '600',
            style: 'normal',
        },
        {
            path: '../public/fonts/geist/Geist-Bold.ttf',
            weight: '700',
            style: 'normal',
        },
    ],
    variable: '--font-geist',
})

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body
                className={`${roboto_mono.variable}  ${geist.variable} antialiased dark`}
            >
                {children}
            </body>
        </html>
    )
}
